# Generated by Django 3.1.5 on 2021-01-29 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150, verbose_name='Compañia')),
                ('company_contact', models.CharField(max_length=150, verbose_name='Compañia')),
                ('vehicles', models.IntegerField(verbose_name='Vehículos')),
                ('people', models.IntegerField(verbose_name='Personas')),
                ('truck', models.IntegerField(verbose_name='Camiones')),
                ('pets', models.IntegerField(verbose_name='Mascotas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificación')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
            },
        ),
    ]
