# Generated by Django 3.1.5 on 2021-02-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20210203_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='truck',
        ),
        migrations.AddField(
            model_name='budget',
            name='containers',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Camiones'),
        ),
        migrations.AddField(
            model_name='budget',
            name='motorcycles',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Camiones'),
        ),
        migrations.AddField(
            model_name='budget',
            name='trucks',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Camiones'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='company_contact',
            field=models.CharField(max_length=150, verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='people',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Personas'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='pets',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Mascotas'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='vehicles',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Vehículos'),
        ),
    ]
