# Generated by Django 3.1.5 on 2021-02-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='value',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
