# Generated by Django 3.1.5 on 2021-02-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_prices_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='quantity',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budget',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='budget',
            name='unit_cost',
            field=models.SmallIntegerField(default=0),
        ),
    ]
