# Generated by Django 3.1.5 on 2021-02-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_auto_20210205_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='price',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prices',
            name='value',
            field=models.SmallIntegerField(default=0),
        ),
    ]
