# Generated by Django 3.1.5 on 2021-02-15 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
        ('budget', '0007_auto_20210206_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Autor'),
        ),
    ]
