# Generated by Django 3.1.5 on 2021-03-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_auto_20210214_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='foreing',
            field=models.BooleanField(default=False, verbose_name='Foraneo'),
            preserve_default=False,
        ),
    ]
