# Generated by Django 3.1.5 on 2021-02-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210204_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='executive',
            field=models.CharField(default=1, max_length=150, verbose_name='Ejecutivo'),
            preserve_default=False,
        ),
    ]
